### ISSUE TITLE
shapy does not work in a docker container

### ISSUE THREAD

**Issue by andyhu-hz** [praus/shapy#1]
Run python example.py will get error as below

07:29:45 shapy.framework.executor ERROR: [1] sudo modprobe ifb [modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.1.12-boot2docker/modules.dep.bin']
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
07:29:45 shapy.emulation.shaper INFO: Configuring 127.0.0.2 -> U:1024kbps D:1024kbps delay:5ms jitter:±5ms
07:29:45 shapy.framework.executor ERROR: [1] sudo ip link show dev ifb1 [Device "ifb1" does not exist.]
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
07:29:45 shapy.framework.executor ERROR: [1] sudo ip link show dev ifb0 [Device "ifb0" does not exist.]
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
07:29:45 shapy.emulation.shaper INFO: Configuring 127.0.0.4 -> U:256kbps D:512kbps delay:20ms jitter:±0ms
07:29:45 shapy.framework.executor ERROR: [1] sudo ip link show dev ifb1 [Device "ifb1" does not exist.]
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
07:29:45 shapy.framework.executor ERROR: [1] sudo ip link show dev ifb0 [Device "ifb0" does not exist.]
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
07:29:45 shapy.emulation.shaper INFO: Configuring 127.0.0.3 -> U:256kbps D:512kbps delay:20ms jitter:±0ms
07:29:45 shapy.framework.executor ERROR: [1] sudo ip link show dev ifb1 [Device "ifb1" does not exist.]
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
07:29:45 shapy.framework.executor ERROR: [1] sudo ip link show dev ifb0 [Device "ifb0" does not exist.]
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
07:29:45 shapy.emulation.shaper INFO: Setting up shaping/emulation on interface lo:
07:29:45 shapy.framework.executor INFO: [0] sudo ip link show dev lo
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    sh.set_shaping(ps)
  File "/usr/local/lib/python2.7/dist-packages/shapy/emulation/shaper.py", line 124, in set_shaping
    shapy.Interface(i).set_shaping()
  File "/usr/local/lib/python2.7/dist-packages/shapy/framework/interface.py", line 39, in set_shaping
    self.ingress.execute()
  File "/usr/local/lib/python2.7/dist-packages/shapy/framework/netlink/**init**.py", line 30, in execute
    resp = connection.recv()
  File "/usr/local/lib/python2.7/dist-packages/shapy/framework/netlink/connection.py", line 39, in recv
    raise err
OSError: Netlink error: Operation not permitted (1) | msg: 0\x00\x00\x00$\x00\x05\x06\x01\x00\x00\x00_\x01\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\xff\xff\xf1\xff\xff\xff\x00\x00\x00\x00\x0c\x00\x01\x00ingress\x00

---

 Run teardown get below errors
07:16:06 ERROR: [1] sudo modprobe ifb [modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.1.12-boot2docker/modules.dep.bin']
07:16:06 INFO: [0] sudo ip link show dev lo
07:16:06 INFO: Tearing down lo
07:16:06 INFO: [0] sudo ip link show dev lo
07:16:06 ERROR: [2] sudo tc qdisc del dev lo root [RTNETLINK answers: Operation not permitted]
07:16:06 ERROR: [2] sudo tc qdisc del dev lo ingress [RTNETLINK answers: Operation not permitted]
07:16:06 INFO: Tearing down IFBs
Tearing down all interfaces: lo
This will clear entire Traffic Control configuration and unload IFB module.
Please note reported errors usually do not mean anything bad, just that there was nothing to tear down on that particular interface.
07:16:06 ERROR: [1] sudo rmmod ifb [rmmod: ERROR: Module ifb is not currently loaded]

**Comment by andyhu-hz** [comment]
## Run my test code:

#!/usr/bin/python
import logging
from shapy import register_settings
register_settings('settings')
from shapy.emulation.shaper import *
from shapy.framework.interface import *
from shapy.framework.qdisc import *
from shapy.framework.filter import *
from shapy.framework.tcclass import *

if **name** == '**main**':
    lo = Interface('eth0')
    h1 = HTBQdisc('1:', default_class='1ff')
    h1.add( FlowFilter('dst 192.168.1.165', '1:1', prio=1) )
    h1.add( HTBClass('1:1', rate=100, ceil=100) )
    lo.add( h1 )
    lo.set_shaping()

---

Get this error:
Traceback (most recent call last):
  File "tt.py", line 17, in <module>
    lo.set_shaping()
  File "/usr/local/lib/python2.7/dist-packages/shapy/framework/interface.py", line 43, in set_shaping
    self.**traverse_tree(self.root)
  File "/usr/local/lib/python2.7/dist-packages/shapy/framework/interface.py", line 59, in __traverse_tree
    element.execute()
  File "/usr/local/lib/python2.7/dist-packages/shapy/framework/netlink/__init**.py", line 30, in execute
    resp = connection.recv()
  File "/usr/local/lib/python2.7/dist-packages/shapy/framework/netlink/connection.py", line 39, in recv
    raise err
OSError: Netlink error: Operation not permitted (1) | msg: H\x00\x00\x00$\x00\x05\x06\x01\x00\x00\x00\xa7\x01\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x01\x00\xff\xff\xff\xff\x00\x00\x00\x00\x08\x00\x01\x00htb\x00\x1c\x00\x02\x00\x18\x00\x02\x00\x03\x00\x00\x00\n\x00\x00\x00\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00

**Comment by andyhu-hz** [comment]
My test code works fine in a Ubuntu VM , but does not work in a Ubuntu Docker container. I don't know how to resolve this issue. And I am sure my test code run under root user, why the Netlink error info is "Operation not permitted (1)".

**Comment by praus** [comment]
Hi, I don't have much experience with Docker but it seems the kernel prevents apps in the container from changing some kernel settings even though they're running as root. This is to be expected. Your container doesn't have its own kernel but runs on the kernel shared with (potentially) many other containers so it can't be allowed to touch settings of the underlying kernel.

I'm resolving the issue, feel free to reopen.
